/**
 * The career store: lore's facts merged with this repo's presentation overrides.
 *
 * Two inputs, two different owners:
 *
 *   content/career.json   generated by lore's /cv-sync. Facts — clients, dates,
 *                         technologies, outcomes. Never hand-edited; regenerated
 *                         wholesale on every sync.
 *   overrides/*.yaml      this repo's. How those facts READ on a CV. Survives
 *                         every sync, because the sync never touches it.
 *
 * Read modes matter more than they look. `public` is for the deployed site and
 * anonymises clients; `private` is for a CV going to a named recipient and uses
 * real names. Public is the default so that forgetting to set it fails safe.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { load as loadYaml } from 'js-yaml';

const ROOT = process.cwd();

export type Mode = 'public' | 'private';
export type Proficiency = 'Expert' | 'Proficient' | 'Familiar';

// --- Shapes emitted by cv-sync ---------------------------------------------

interface RawClient {
  name: string;
  slug: string;
  publicSlug: string;
  publicName: string;
  public: boolean;
  industry: string | null;
  location: string | null;
  relationship: string | null;
  summary: string;
}

interface RawProject {
  name: string;
  slug: string;
  client: string | null;
  clientPublic: boolean;
  projectType: string | null;
  employment: string | null;
  skills: string[];
  technologies: string[];
  start: string;
  end: string;
  outcome: string;
  featured: boolean;
  tags: string[];
  body: string;
  leaks: { title: string[]; outcome: string[]; body: string[] };
  publicSafe: boolean;
}

interface RawRole {
  name: string;
  slug: string;
  title: string | null;
  employer: string | null;
  start: string;
  end: string;
  skills: string[];
  technologies: string[];
  body: string;
}

interface RawCapability {
  name: string;
  slug: string;
  kind: 'skill' | 'technology';
  category: string | null;
  proficiency: Proficiency | null;
  vendor?: string | null;
  featured: boolean;
  enables?: string[];
  description: string;
  /** Non-public clients named in the description, per cv-sync. */
  descriptionLeaks?: string[];
}

interface RawCredential {
  name: string;
  slug: string;
  issuer: string | null;
  obtained: string;
  body: string;
}

interface RawCommunity {
  name: string;
  slug: string;
  organisation: string | null;
  kind: string | null;
  start: string;
  end: string;
  body: string;
}

interface Career {
  generated: string;
  source: { repo: string; commit: string | null };
  counts: Record<string, number>;
  roles: RawRole[];
  projects: RawProject[];
  skills: RawCapability[];
  technologies: RawCapability[];
  clients: RawClient[];
  projectTypes: { name: string; slug: string; description: string }[];
  credentials: RawCredential[];
  community: RawCommunity[];
  evidence: Record<string, Record<string, string[]>>;
  warnings: { unresolved: string[]; notes: string[] };
}

// --- Overrides --------------------------------------------------------------

export interface ProjectOverride {
  publicTitle?: string;
  publicOutcome?: string;
  headline?: string;
  bullet?: string;
  weight?: number;
  draft?: boolean;
  hidden?: boolean;
}

export interface SiteConfig {
  name: string;
  tagline: string;
  location: string;
  email: string;
  phone: string;
  linkedin: string;
  linkedinUrl: string;
  github: string;
  githubUrl: string;
  earlier: string;
  profiles: Record<string, string>;
}

function readJson<T>(...parts: string[]): T {
  return JSON.parse(readFileSync(join(ROOT, ...parts), 'utf-8')) as T;
}

function readYaml<T>(fallback: T, ...parts: string[]): T {
  try {
    return (loadYaml(readFileSync(join(ROOT, ...parts), 'utf-8')) as T) ?? fallback;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return fallback;
    throw error;
  }
}

export interface RoleOverride {
  summary?: string;
  /** Named clients. Private mode only — this line names organisations outright. */
  clients?: string;
  /** Anonymised equivalent, safe for the public site. */
  publicClients?: string;
  bullets?: { text: string; personas?: string[] }[];
}

export interface Persona {
  key: string;
  label: string;
  description: string;
  profile: string;
  skills?: string[];
  technologies?: string[];
  projects?: string[];
}

const career = readJson<Career>('content', 'career.json');

const overrides =
  readYaml<{ projects?: Record<string, ProjectOverride> }>({}, 'overrides', 'projects.yaml')
    .projects ?? {};

const roleFile = readYaml<{ roles?: Record<string, RoleOverride>; hidden?: string[] }>(
  {},
  'overrides',
  'roles.yaml',
);
const roleOverrides = roleFile.roles ?? {};
const hiddenRoles = new Set(roleFile.hidden ?? []);

const personaFile = readYaml<{ personas?: Record<string, Omit<Persona, 'key'>> }>(
  {},
  'overrides',
  'personas.yaml',
).personas ?? {};

export const personas: Persona[] = Object.entries(personaFile).map(([key, value]) => ({
  key,
  ...value,
}));

export function persona(key: string): Persona | undefined {
  return personas.find((p) => p.key === key);
}

export const config = readYaml<SiteConfig>({} as SiteConfig, 'config.yaml');

// --- Resolved view ----------------------------------------------------------

export interface Project {
  /** URL slug. In public mode this derives from the public title, never the lore name. */
  slug: string;
  /** Stable key from lore, used for evidence lookups. Never appears in a URL. */
  loreSlug: string;
  loreName: string;
  title: string;
  client: string | null;
  clientAnonymised: boolean;
  industry: string | null;
  projectType: string | null;
  employment: string | null;
  skills: string[];
  technologies: string[];
  start: string;
  end: string;
  year: number | null;
  summary: string;
  story: string;
  featured: boolean;
  tags: string[];
  draft: boolean;
}

const clientsByName = new Map(career.clients.map((c) => [c.name, c]));

export function resolveMode(): Mode {
  return process.env.CV_MODE === 'private' ? 'private' : 'public';
}

/** Must match slugify() in lore's docs/cv-sync.py — the two generate the same URLs. */
export function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'untitled';
}

function year(value: string): number | null {
  const match = /^(\d{4})/.exec(value);
  return match ? Number(match[1]) : null;
}

/**
 * In public mode a project is only publishable when cv-sync cleared it, or when
 * an override supplies replacement wording for whatever it flagged. Fail closed:
 * a project with no override and a flagged title simply does not render.
 */
function publishable(raw: RawProject, override: ProjectOverride, mode: Mode): boolean {
  if (override.hidden) return false;
  if (mode === 'private') return true;
  if (raw.publicSafe) return true;
  const titleCovered = raw.leaks.title.length === 0 || Boolean(override.publicTitle);
  const outcomeCovered = raw.leaks.outcome.length === 0 || Boolean(override.publicOutcome);
  return titleCovered && outcomeCovered;
}

function toProject(raw: RawProject, override: ProjectOverride, mode: Mode): Project {
  const client = raw.client ? clientsByName.get(raw.client) ?? null : null;
  const anonymise = mode === 'public' && client !== null && !client.public;
  const title = (mode === 'public' && override.publicTitle) || override.headline || raw.name;

  return {
    // lore names projects after their clients, so the lore slug would put the
    // client straight in the URL bar. Public URLs derive from the public title.
    slug: anonymise ? slugify(override.headline || title) : raw.slug,
    loreSlug: raw.slug,
    loreName: raw.name,
    title,
    client: client ? (anonymise ? client.publicName : client.name) : null,
    clientAnonymised: anonymise,
    industry: client?.industry ?? null,
    projectType: raw.projectType,
    employment: raw.employment,
    skills: raw.skills,
    technologies: raw.technologies,
    start: raw.start,
    end: raw.end,
    year: year(raw.end) ?? year(raw.start),
    summary:
      override.bullet ||
      ((mode === 'public' && override.publicOutcome) || raw.outcome),
    // Body prose is written for lore and quotes clients freely, so it is only
    // ever exposed in private mode. The portfolio shows the outcome line.
    story: mode === 'private' ? raw.body : '',
    featured: raw.featured,
    tags: raw.tags,
    draft: Boolean(override.draft),
  };
}

/**
 * A persona selects projects by the capabilities it claims: if a persona lists
 * Snowflake, the Snowflake projects are its evidence. That keeps one tick-list
 * driving both the skills section and the project selection, instead of asking
 * for the same information twice.
 */
function matchesPersona(project: Project, chosen: Persona | undefined): boolean {
  if (!chosen) return true;
  if (chosen.projects?.length) return chosen.projects.includes(project.loreName);
  const wanted = new Set([...(chosen.skills ?? []), ...(chosen.technologies ?? [])]);
  if (wanted.size === 0) return true;
  return [...project.skills, ...project.technologies].some((item) => wanted.has(item));
}

export function projects(mode: Mode = resolveMode(), lens = 'all'): Project[] {
  const chosen = lens === 'all' ? undefined : persona(lens);
  return career.projects
    .map((raw) => ({ raw, override: overrides[raw.name] ?? {} }))
    .filter(({ raw, override }) => publishable(raw, override, mode))
    .map(({ raw, override }) => toProject(raw, override, mode))
    .filter((project) => matchesPersona(project, chosen))
    .sort((a, b) => {
      const weight = (overrides[b.loreName]?.weight ?? 0) - (overrides[a.loreName]?.weight ?? 0);
      if (weight !== 0) return weight;
      if (a.featured !== b.featured) return a.featured ? -1 : 1;
      return (b.year ?? 0) - (a.year ?? 0);
    });
}

export interface Bullet {
  text: string;
  personas: string[];
}

export interface Role {
  slug: string;
  loreName: string;
  title: string;
  employer: string;
  clients: string;
  start: string;
  end: string;
  summary: string;
  bullets: Bullet[];
  skills: string[];
  technologies: string[];
}

/**
 * `lens` filters bullets the way the old CSV `personas` column did: a bullet with
 * no personas listed appears only under `all`.
 */
export function roles(lens = 'all', mode: Mode = resolveMode()): Role[] {
  return career.roles
    .filter((raw) => !hiddenRoles.has(raw.name))
    .map((raw) => {
      const override = roleOverrides[raw.name] ?? {};
      const bullets = (override.bullets ?? []).map((bullet) => ({
        text: bullet.text,
        personas: bullet.personas ?? [],
      }));
      return {
        slug: raw.slug,
        loreName: raw.name,
        title: raw.title ?? raw.name,
        // Employers are always public per lore's rule, so no anonymisation here.
        employer: raw.employer ?? '',
        // A "Key clients" line names organisations outright, which is fine on a
        // CV going to one recipient and not on the open web.
        clients: mode === 'private' ? override.clients ?? '' : override.publicClients ?? '',
        start: raw.start,
        end: raw.end,
        summary: override.summary ?? raw.body,
        bullets:
          lens === 'all' ? bullets : bullets.filter((b) => b.personas.includes(lens)),
        skills: raw.skills,
        technologies: raw.technologies,
      };
    })
    .sort((a, b) => {
      const rank = (value: string) => (value === 'present' ? 9999 : year(value) ?? 0);
      return rank(b.end) - rank(a.end);
    });
}

export interface CapabilityGroup {
  domain: string;
  categories: { category: string; items: RawCapability[] }[];
}

/**
 * lore keeps skills (practices) and technologies (tools) as separate entity
 * types. The CV shows them together under one Capabilities heading, so the
 * split becomes the top-level grouping rather than being flattened away.
 */
export function capabilities(lens = 'all'): CapabilityGroup[] {
  const chosen = lens === 'all' ? undefined : persona(lens);
  const groups: [string, RawCapability[], string[] | undefined][] = [
    ['Skills', career.skills, chosen?.skills],
    ['Technologies', career.technologies, chosen?.technologies],
  ];
  return groups
    .map(([domain, items, wanted]) => {
      const selected = wanted?.length ? items.filter((i) => wanted.includes(i.name)) : items;
      const byCategory = new Map<string, RawCapability[]>();
      for (const item of selected) {
        const key = item.category ?? 'Other';
        if (!byCategory.has(key)) byCategory.set(key, []);
        byCategory.get(key)!.push(item);
      }
      return {
        domain,
        categories: [...byCategory.entries()]
          .map(([category, list]) => ({ category, items: list }))
          .sort((a, b) => a.category.localeCompare(b.category)),
      };
    })
    .filter((group) => group.categories.length > 0);
}

/** Projects evidencing a capability — lore's backlinks, resolved at build time. */
export function evidenceFor(kind: 'skill' | 'technology', name: string, mode: Mode = resolveMode()): Project[] {
  const slugs = new Set(career.evidence[kind]?.[name] ?? []);
  return projects(mode).filter((project) => slugs.has(project.loreSlug));
}

export interface Capability extends RawCapability {
  evidenceCount: number;
}

/** Skills and technologies as one flat list, each with its evidence count. */
/**
 * Descriptions come from lore bodies, written without a public reader in mind, so
 * one that names a non-public client is withheld rather than published — same
 * fail-closed rule the project bodies follow.
 */
function safeDescription(item: RawCapability, mode: Mode): string {
  if (mode === 'private') return item.description;
  return item.descriptionLeaks?.length ? '' : item.description;
}

export function allCapabilities(mode: Mode = resolveMode()): Capability[] {
  // Evidence is keyed by lore slug, which is stable across modes.
  const visible = new Set(projects(mode).map((p) => p.loreSlug));
  const count = (kind: 'skill' | 'technology', name: string) =>
    (career.evidence[kind]?.[name] ?? []).filter((slug) => visible.has(slug)).length;

  return [...career.skills, ...career.technologies]
    .map((item) => ({
      ...item,
      description: safeDescription(item, mode),
      evidenceCount: count(item.kind, item.name),
    }))
    .sort((a, b) => b.evidenceCount - a.evidenceCount || a.name.localeCompare(b.name));
}

export function capabilityBySlug(slug: string, mode: Mode = resolveMode()): Capability | undefined {
  return allCapabilities(mode).find((item) => item.slug === slug);
}

export function projectBySlug(slug: string, mode: Mode = resolveMode()): Project | undefined {
  return projects(mode).find((project) => project.slug === slug);
}

export interface Facet {
  key: string;
  label: string;
  values: { value: string; count: number }[];
}

/**
 * Filter options for the project index, counted from what's actually visible in
 * this mode — so an anonymised build never offers a facet nobody can see.
 */
export function facets(mode: Mode = resolveMode()): Facet[] {
  const visible = projects(mode);
  const tally = (pick: (p: Project) => (string | null)[]): { value: string; count: number }[] => {
    const counts = new Map<string, number>();
    for (const project of visible) {
      for (const value of pick(project)) {
        if (value) counts.set(value, (counts.get(value) ?? 0) + 1);
      }
    }
    return [...counts.entries()]
      .map(([value, count]) => ({ value, count }))
      .sort((a, b) => b.count - a.count || a.value.localeCompare(b.value));
  };

  return [
    { key: 'client', label: 'Client', values: tally((p) => [p.client]) },
    { key: 'industry', label: 'Industry', values: tally((p) => [p.industry]) },
    { key: 'type', label: 'Type of work', values: tally((p) => [p.projectType]) },
    { key: 'technology', label: 'Technology', values: tally((p) => p.technologies) },
    { key: 'skill', label: 'Skill', values: tally((p) => p.skills) },
    { key: 'year', label: 'Year', values: tally((p) => [p.year ? String(p.year) : null]) },
  ].filter((facet) => facet.values.length > 1);
}

export function proficiencySegments(proficiency: Proficiency | null): number {
  if (proficiency === 'Expert') return 3;
  if (proficiency === 'Proficient') return 2;
  if (proficiency === 'Familiar') return 1;
  return 0;
}

export const credentials = career.credentials;
export const community = career.community;
export const projectTypes = career.projectTypes;
export const clients = career.clients;
export const meta = { generated: career.generated, source: career.source, counts: career.counts };
