/**
 * The career store: lore's facts merged with this repo's presentation overrides.
 *
 * Two inputs, two different owners:
 *
 *   content/career.json   generated by lore's /cv-sync. Facts - clients, dates,
 *                         technologies, outcomes. Never hand-edited; regenerated
 *                         wholesale on every sync.
 *   overrides/*.yaml      this repo's. How those facts READ on a CV. Survives
 *                         every sync, because the sync never touches it.
 *
 * Read modes matter more than they look. `public` is for the deployed site and
 * anonymises clients; `private` is for a CV going to a named recipient and uses
 * real names. Public is the default so that forgetting to set it fails safe.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { load as loadYaml } from 'js-yaml';

const ROOT = process.cwd();

export type Mode = 'public' | 'private';
export type Proficiency = 'Expert' | 'Proficient' | 'Familiar';

// --- Shapes emitted by cv-sync ---------------------------------------------

interface RawClient {
  name: string;
  slug: string;
  publicSlug: string;
  publicName: string;
  public: boolean;
  aliases: string[];
  industry: string | null;
  location: string | null;
  relationship: string | null;
  summary: string;
}

interface RawProject {
  name: string;
  slug: string;
  client: string | null;
  clientPublic: boolean;
  projectType: string | null;
  employment: string | null;
  skills: string[];
  technologies: string[];
  start: string;
  end: string;
  outcome: string;
  featured: boolean;
  tags: string[];
  body: string;
  leaks: { title: string[]; outcome: string[]; body: string[] };
  publicSafe: boolean;
}

interface RawRole {
  name: string;
  slug: string;
  title: string | null;
  employer: string | null;
  start: string;
  end: string;
  skills: string[];
  technologies: string[];
  body: string;
}

interface RawCapability {
  name: string;
  slug: string;
  kind: 'skill' | 'technology';
  category: string | null;
  proficiency: Proficiency | null;
  vendor?: string | null;
  featured: boolean;
  enables?: string[];
  description: string;
  /** Non-public clients named in the description, per cv-sync. */
  descriptionLeaks?: string[];
}

interface RawCredential {
  name: string;
  slug: string;
  issuer: string | null;
  obtained: string;
  body: string;
}

interface RawCommunity {
  name: string;
  slug: string;
  organisation: string | null;
  kind: string | null;
  start: string;
  end: string;
  body: string;
}

interface Career {
  generated: string;
  source: { repo: string; commit: string | null };
  counts: Record<string, number>;
  roles: RawRole[];
  projects: RawProject[];
  skills: RawCapability[];
  technologies: RawCapability[];
  clients: RawClient[];
  projectTypes: { name: string; slug: string; description: string }[];
  credentials: RawCredential[];
  community: RawCommunity[];
  evidence: Record<string, Record<string, string[]>>;
  warnings: { unresolved: string[]; notes: string[] };
}

// --- Overrides --------------------------------------------------------------

export interface ProjectOverride {
  publicTitle?: string;
  publicOutcome?: string;
  headline?: string;
  bullet?: string;
  weight?: number;
  draft?: boolean;
  hidden?: boolean;
}

export interface SiteConfig {
  name: string;
  tagline: string;
  location: string;
  email: string;
  phone: string;
  linkedin: string;
  linkedinUrl: string;
  github: string;
  githubUrl: string;
  earlier: string;
  profiles: Record<string, string>;
}

function readJson<T>(...parts: string[]): T {
  return JSON.parse(readFileSync(join(ROOT, ...parts), 'utf-8')) as T;
}

function readYaml<T>(fallback: T, ...parts: string[]): T {
  try {
    return (loadYaml(readFileSync(join(ROOT, ...parts), 'utf-8')) as T) ?? fallback;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return fallback;
    throw error;
  }
}

export interface RoleOverride {
  summary?: string;
  /** Named clients. Private mode only - this line names organisations outright. */
  clients?: string;
  /** Anonymised equivalent, safe for the public site. */
  publicClients?: string;
  bullets?: { text: string; personas?: string[] }[];
}

export interface Persona {
  key: string;
  label: string;
  description: string;
  profile: string;
  skills?: string[];
  technologies?: string[];
  projects?: string[];
}

const career = readJson<Career>('content', 'career.json');

const overrides =
  readYaml<{ projects?: Record<string, ProjectOverride> }>({}, 'overrides', 'projects.yaml')
    .projects ?? {};

const roleFile = readYaml<{ roles?: Record<string, RoleOverride>; hidden?: string[] }>(
  {},
  'overrides',
  'roles.yaml',
);
const roleOverrides = roleFile.roles ?? {};
const hiddenRoles = new Set(roleFile.hidden ?? []);

const personaFile = readYaml<{ personas?: Record<string, Omit<Persona, 'key'>> }>(
  {},
  'overrides',
  'personas.yaml',
).personas ?? {};

export const personas: Persona[] = Object.entries(personaFile).map(([key, value]) => ({
  key,
  ...value,
  profile: deDash(value.profile ?? ''),
}));

export function persona(key: string): Persona | undefined {
  return personas.find((p) => p.key === key);
}

export const config = readYaml<SiteConfig>({} as SiteConfig, 'config.yaml');

// --- Resolved view ----------------------------------------------------------

// --- Publishing lore prose --------------------------------------------------

/**
 * lore bodies are written for lore, not for the web. They name clients outright,
 * cross-reference other entities as [[wikilinks]], and carry lore's own margin
 * notes. Publishing one means resolving all three:
 *
 *   [[wikilinks]]  become links where the target is publishable, and plain public
 *                  wording where it isn't.
 *   client names   become "the client" (this project's own) or the client's public
 *                  descriptor (anyone else's).
 *   margin notes   a paragraph that is entirely italicised is lore's bookkeeping
 *                  ("P003 - the 2026 extraction entry was folded in here"). It
 *                  records an ingest decision, not the engagement. Dropped.
 *
 * Identifier matching mirrors scripts/check_public.py exactly - full names and
 * aliases of four characters or more, on word boundaries. That script reads the
 * built HTML and is the backstop if this misses one.
 */

/** Matches MIN_ALIAS in check_public.py: "VIA" would otherwise match "via". */
const MIN_ALIAS = 4;

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

const nonPublicIdentifiers = career.clients
  .filter((client) => !client.public)
  .flatMap((client) =>
    [client.name, ...(client.aliases ?? [])]
      .filter((identifier) => identifier.length >= MIN_ALIAS)
      .map((identifier) => ({ identifier, client })),
  )
  // Longest first, so "Silverchain Group" is spent before "Silverchain" can eat
  // its first word and strand the rest of the phrase in the output.
  .sort((a, b) => b.identifier.length - a.identifier.length)
  .map(({ identifier, client }) => ({
    client,
    pattern: new RegExp(`(?<![A-Za-z0-9])${escapeRegExp(identifier)}(?![A-Za-z0-9])`, 'gi'),
  }));

/** "Global energy major" reads as "a global energy major" inside a sentence. */
function withArticle(descriptor: string): string {
  const lower = descriptor.charAt(0).toLowerCase() + descriptor.slice(1);
  return `${/^[aeiou]/i.test(lower) ? 'an' : 'a'} ${lower}`;
}

function scrubClientNames(text: string, own: string | null, mode: Mode): string {
  if (mode === 'private') return text;
  let out = text;
  for (const { client, pattern } of nonPublicIdentifiers) {
    out = out.replace(pattern, client.name === own ? 'the client' : withArticle(client.publicName));
  }
  // A replacement inherits the sentence position of the name it replaced.
  return out.replace(/(^|[.!?]\s+)the client/g, (_, lead: string) => `${lead}The client`);
}

/**
 * Em dashes are lore's house style, not this site's. A dash introducing a list
 * becomes a colon; one introducing a clause becomes a comma. The tell is whether
 * the rest of the sentence carries a comma, which is what separates
 * "processes — payroll, HR and finance" from "the enterprise — the largest of
 * its type". Titles and other repo-authored copy are written without them.
 */
export function deDash(text: string): string {
  return text.replace(/\s+—\s+/g, (_match, offset: number, whole: string) => {
    const rest = whole.slice(offset);
    const stop = rest.search(/[.!?](\s|$)/);
    const clause = stop === -1 ? rest : rest.slice(0, stop);
    return clause.includes(',') ? ': ' : ', ';
  });
}

function inline(text: string): string {
  return escapeHtml(deDash(text))
    // Links in lore bodies point at lore's own docs - keep the label, drop the path.
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>');
}

const capabilityByName = new Map(
  [...career.skills, ...career.technologies].map((item) => [item.name, item] as const),
);
const projectByName = new Map(career.projects.map((raw) => [raw.name, raw] as const));

function resolveWikilink(label: string, own: string | null, mode: Mode): string {
  const capability = capabilityByName.get(label);
  if (capability) {
    return `<a href="/capabilities/${capability.slug}">${escapeHtml(capability.name)}</a>`;
  }

  const raw = projectByName.get(label);
  if (raw) {
    const override = overrides[raw.name] ?? {};
    const title = displayTitle(raw, override, mode);
    if (publishable(raw, override, mode)) {
      return `<a href="/projects/${slugTable(mode).get(raw.slug)}">${escapeHtml(title)}</a>`;
    }
    // Withheld: name it only if an override supplied public wording for it.
    const withheld = mode === 'public' ? override.publicTitle ?? 'a related engagement' : title;
    return escapeHtml(withheld);
  }

  return inline(scrubClientNames(label, own, mode));
}

function renderProse(text: string, own: string | null, mode: Mode): string {
  return text
    .split(/(\[\[[^\]]+\]\])/g)
    .map((part) => {
      const link = /^\[\[([^\]]+)\]\]$/.exec(part);
      return link
        ? resolveWikilink(link[1], own, mode)
        : inline(scrubClientNames(part, own, mode));
    })
    .join('');
}

/** Body prose as ready-to-render HTML paragraphs, margin notes removed. */
function story(raw: RawProject, mode: Mode): string[] {
  return raw.body
    .split(/\n{2,}/)
    .map((para) => para.trim().replace(/\n/g, ' '))
    .filter((para) => para !== '' && !/^\*[^*]+\*$/.test(para))
    .map((para) => renderProse(para, raw.client, mode));
}

export interface Project {
  /** URL slug. In public mode this is composed from public wording, never the lore name. */
  slug: string;
  /** Stable key from lore, used for evidence lookups. Never appears in a URL. */
  loreSlug: string;
  loreName: string;
  title: string;
  client: string | null;
  clientAnonymised: boolean;
  industry: string | null;
  projectType: string | null;
  employment: string | null;
  skills: string[];
  technologies: string[];
  start: string;
  end: string;
  year: number | null;
  summary: string;
  /** The lore write-up, made publishable: HTML paragraphs, safe to set:html. */
  story: string[];
  featured: boolean;
  tags: string[];
  draft: boolean;
}

const clientsByName = new Map(career.clients.map((c) => [c.name, c]));

export function resolveMode(): Mode {
  return process.env.CV_MODE === 'private' ? 'private' : 'public';
}

/** Must match slugify() in lore's docs/cv-sync.py - the two generate the same URLs. */
export function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'untitled';
}

function year(value: string): number | null {
  const match = /^(\d{4})/.exec(value);
  return match ? Number(match[1]) : null;
}

/**
 * In public mode a project is only publishable when cv-sync cleared it, or when
 * an override supplies replacement wording for whatever it flagged. Fail closed:
 * a project with no override and a flagged title simply does not render.
 */
function publishable(raw: RawProject, override: ProjectOverride, mode: Mode): boolean {
  if (override.hidden) return false;
  if (mode === 'private') return true;
  if (raw.publicSafe) return true;
  const titleCovered = raw.leaks.title.length === 0 || Boolean(override.publicTitle);
  const outcomeCovered = raw.leaks.outcome.length === 0 || Boolean(override.publicOutcome);
  return titleCovered && outcomeCovered;
}

function anonymised(raw: RawProject, mode: Mode): RawClient | null {
  const client = raw.client ? clientsByName.get(raw.client) ?? null : null;
  return mode === 'public' && client !== null && !client.public ? client : null;
}

function displayTitle(raw: RawProject, override: ProjectOverride, mode: Mode): string {
  return (mode === 'public' && override.publicTitle) || override.headline || raw.name;
}

/**
 * Public slugs are composed, not derived. A public title says what the work was
 * ("Rostering review") and leaves who it was for to the client line beside it, so
 * titles repeat across clients and a title-only slug would collide. The client's
 * publicSlug disambiguates - cv-sync generates it never to encode a real name.
 *
 * Built once per mode over lore's own project order, so a slug never moves
 * because a sibling was edited.
 */
const slugTables = new Map<Mode, Map<string, string>>();

function slugTable(mode: Mode): Map<string, string> {
  const cached = slugTables.get(mode);
  if (cached) return cached;

  const table = new Map<string, string>();
  const taken = new Set<string>();
  for (const raw of career.projects) {
    const client = anonymised(raw, mode);
    let slug = raw.slug;
    if (client) {
      const override = overrides[raw.name] ?? {};
      const base = `${slugify(displayTitle(raw, override, mode))}-${client.publicSlug}`;
      slug = base;
      for (let n = 2; taken.has(slug); n += 1) slug = `${base}-${n}`;
    }
    taken.add(slug);
    table.set(raw.slug, slug);
  }

  slugTables.set(mode, table);
  return table;
}

function toProject(raw: RawProject, override: ProjectOverride, mode: Mode): Project {
  const client = raw.client ? clientsByName.get(raw.client) ?? null : null;
  const anonymise = anonymised(raw, mode) !== null;
  const title = displayTitle(raw, override, mode);

  return {
    // lore names projects after their clients, so the lore slug would put the
    // client straight in the URL bar. Public URLs are composed from public wording.
    slug: slugTable(mode).get(raw.slug)!,
    loreSlug: raw.slug,
    loreName: raw.name,
    title,
    client: client ? (anonymise ? client.publicName : client.name) : null,
    clientAnonymised: anonymise,
    industry: client?.industry ?? null,
    projectType: raw.projectType,
    employment: raw.employment,
    skills: raw.skills,
    technologies: raw.technologies,
    start: raw.start,
    end: raw.end,
    year: year(raw.end) ?? year(raw.start),
    summary: deDash(
      override.bullet || ((mode === 'public' && override.publicOutcome) || raw.outcome),
    ),
    story: story(raw, mode),
    featured: raw.featured,
    tags: raw.tags,
    draft: Boolean(override.draft),
  };
}

/**
 * A persona selects projects by the capabilities it claims: if a persona lists
 * Snowflake, the Snowflake projects are its evidence. That keeps one tick-list
 * driving both the skills section and the project selection, instead of asking
 * for the same information twice.
 */
function matchesPersona(project: Project, chosen: Persona | undefined): boolean {
  if (!chosen) return true;
  if (chosen.projects?.length) return chosen.projects.includes(project.loreName);
  const wanted = new Set([...(chosen.skills ?? []), ...(chosen.technologies ?? [])]);
  if (wanted.size === 0) return true;
  return [...project.skills, ...project.technologies].some((item) => wanted.has(item));
}

export function projects(mode: Mode = resolveMode(), lens = 'all'): Project[] {
  const chosen = lens === 'all' ? undefined : persona(lens);
  return career.projects
    .map((raw) => ({ raw, override: overrides[raw.name] ?? {} }))
    .filter(({ raw, override }) => publishable(raw, override, mode))
    .map(({ raw, override }) => toProject(raw, override, mode))
    .filter((project) => matchesPersona(project, chosen))
    .sort((a, b) => {
      const weight = (overrides[b.loreName]?.weight ?? 0) - (overrides[a.loreName]?.weight ?? 0);
      if (weight !== 0) return weight;
      if (a.featured !== b.featured) return a.featured ? -1 : 1;
      return (b.year ?? 0) - (a.year ?? 0);
    });
}

export interface Bullet {
  text: string;
  personas: string[];
}

export interface Role {
  slug: string;
  loreName: string;
  title: string;
  employer: string;
  clients: string;
  start: string;
  end: string;
  summary: string;
  bullets: Bullet[];
  skills: string[];
  technologies: string[];
}

/**
 * `lens` filters bullets the way the old CSV `personas` column did: a bullet with
 * no personas listed appears only under `all`.
 */
export function roles(lens = 'all', mode: Mode = resolveMode()): Role[] {
  return career.roles
    .filter((raw) => !hiddenRoles.has(raw.name))
    .map((raw) => {
      const override = roleOverrides[raw.name] ?? {};
      const bullets = (override.bullets ?? []).map((bullet) => ({
        text: deDash(bullet.text),
        personas: bullet.personas ?? [],
      }));
      return {
        slug: raw.slug,
        loreName: raw.name,
        title: raw.title ?? raw.name,
        // Employers are always public per lore's rule, so no anonymisation here.
        employer: raw.employer ?? '',
        // A "Key clients" line names organisations outright, which is fine on a
        // CV going to one recipient and not on the open web.
        clients: mode === 'private' ? override.clients ?? '' : override.publicClients ?? '',
        start: raw.start,
        end: raw.end,
        summary: deDash(override.summary ?? raw.body),
        bullets:
          lens === 'all' ? bullets : bullets.filter((b) => b.personas.includes(lens)),
        skills: raw.skills,
        technologies: raw.technologies,
      };
    })
    .sort((a, b) => {
      const rank = (value: string) => (value === 'present' ? 9999 : year(value) ?? 0);
      return rank(b.end) - rank(a.end);
    });
}

export interface CapabilityGroup {
  domain: string;
  categories: { category: string; items: RawCapability[] }[];
}

/**
 * lore keeps skills (practices) and technologies (tools) as separate entity
 * types. The CV shows them together under one Capabilities heading, so the
 * split becomes the top-level grouping rather than being flattened away.
 */
export function capabilities(lens = 'all'): CapabilityGroup[] {
  const chosen = lens === 'all' ? undefined : persona(lens);
  const groups: [string, RawCapability[], string[] | undefined][] = [
    ['Skills', career.skills, chosen?.skills],
    ['Technologies', career.technologies, chosen?.technologies],
  ];
  return groups
    .map(([domain, items, wanted]) => {
      const selected = wanted?.length ? items.filter((i) => wanted.includes(i.name)) : items;
      const byCategory = new Map<string, RawCapability[]>();
      for (const item of selected) {
        const key = item.category ?? 'Other';
        if (!byCategory.has(key)) byCategory.set(key, []);
        byCategory.get(key)!.push(item);
      }
      return {
        domain,
        categories: [...byCategory.entries()]
          .map(([category, list]) => ({ category, items: list }))
          .sort((a, b) => a.category.localeCompare(b.category)),
      };
    })
    .filter((group) => group.categories.length > 0);
}

/** Projects evidencing a capability - lore's backlinks, resolved at build time. */
export function evidenceFor(kind: 'skill' | 'technology', name: string, mode: Mode = resolveMode()): Project[] {
  const slugs = new Set(career.evidence[kind]?.[name] ?? []);
  return projects(mode).filter((project) => slugs.has(project.loreSlug));
}

export interface Capability extends RawCapability {
  evidenceCount: number;
  /** The description as renderable HTML paragraphs - same treatment as a project story. */
  descriptionHtml: string[];
}

/**
 * Capability descriptions are lore bodies too, so they go through the same
 * scrubber. `description` stays plain text for <meta description>; the page
 * renders `descriptionHtml`.
 */
function describe(item: RawCapability, mode: Mode): string[] {
  return item.description
    .split(/\n{2,}/)
    .map((para) => para.trim().replace(/\n/g, ' '))
    .filter((para) => para !== '' && !/^\*[^*]+\*$/.test(para))
    .map((para) => renderProse(para, null, mode));
}

/** Plain-text equivalent, for meta tags and anywhere markup would be wrong. */
function safeDescription(item: RawCapability, mode: Mode): string {
  return deDash(scrubClientNames(item.description.replace(/\[\[([^\]]+)\]\]/g, '$1'), null, mode));
}

export function allCapabilities(mode: Mode = resolveMode()): Capability[] {
  // Evidence is keyed by lore slug, which is stable across modes.
  const visible = new Set(projects(mode).map((p) => p.loreSlug));
  const count = (kind: 'skill' | 'technology', name: string) =>
    (career.evidence[kind]?.[name] ?? []).filter((slug) => visible.has(slug)).length;

  return [...career.skills, ...career.technologies]
    .map((item) => ({
      ...item,
      description: safeDescription(item, mode),
      descriptionHtml: describe(item, mode),
      evidenceCount: count(item.kind, item.name),
    }))
    .sort((a, b) => b.evidenceCount - a.evidenceCount || a.name.localeCompare(b.name));
}

export function capabilityBySlug(slug: string, mode: Mode = resolveMode()): Capability | undefined {
  return allCapabilities(mode).find((item) => item.slug === slug);
}

export function projectBySlug(slug: string, mode: Mode = resolveMode()): Project | undefined {
  return projects(mode).find((project) => project.slug === slug);
}

export interface Facet {
  key: string;
  label: string;
  values: { value: string; count: number }[];
}

/**
 * Filter options for the project index, counted from what's actually visible in
 * this mode - so an anonymised build never offers a facet nobody can see.
 */
export function facets(mode: Mode = resolveMode()): Facet[] {
  const visible = projects(mode);
  const tally = (pick: (p: Project) => (string | null)[]): { value: string; count: number }[] => {
    const counts = new Map<string, number>();
    for (const project of visible) {
      for (const value of pick(project)) {
        if (value) counts.set(value, (counts.get(value) ?? 0) + 1);
      }
    }
    return [...counts.entries()]
      .map(([value, count]) => ({ value, count }))
      .sort((a, b) => b.count - a.count || a.value.localeCompare(b.value));
  };

  return [
    { key: 'client', label: 'Client', values: tally((p) => [p.client]) },
    { key: 'industry', label: 'Industry', values: tally((p) => [p.industry]) },
    { key: 'type', label: 'Type of work', values: tally((p) => [p.projectType]) },
    { key: 'technology', label: 'Technology', values: tally((p) => p.technologies) },
    { key: 'skill', label: 'Skill', values: tally((p) => p.skills) },
    { key: 'year', label: 'Year', values: tally((p) => [p.year ? String(p.year) : null]) },
  ].filter((facet) => facet.values.length > 1);
}

export interface Focus {
  name: string;
  slug: string;
  summary: string;
  count: number;
}

/**
 * lore's project types, as a "what I do" list. Their descriptions are lore bodies
 * that open with the definition and then trail off into ingest bookkeeping
 * ("Draft capability proposed during ingest - confirm, rename or cut"), so only
 * the opening sentence is published. A sentence ends at a full stop followed by a
 * capital, which keeps "etc. as they come up" in one piece.
 */
export function focuses(mode: Mode = resolveMode()): Focus[] {
  const visible = projects(mode);
  return projectTypes
    .map((type) => ({
      name: type.name,
      slug: type.slug,
      summary: renderProse(
        /^(.+?\.)(?=\s+[A-Z])/.exec(type.description.trim())?.[1] ??
          type.description.trim().split(/\n{2,}/)[0],
        null,
        mode,
      ),
      count: visible.filter((project) => project.projectType === type.name).length,
    }))
    .filter((focus) => focus.count > 0)
    .sort((a, b) => b.count - a.count);
}

export function proficiencySegments(proficiency: Proficiency | null): number {
  if (proficiency === 'Expert') return 3;
  if (proficiency === 'Proficient') return 2;
  if (proficiency === 'Familiar') return 1;
  return 0;
}

export const credentials = career.credentials;
export const community = career.community;
export const projectTypes = career.projectTypes;
export const clients = career.clients;
export const meta = { generated: career.generated, source: career.source, counts: career.counts };
